### ISSUE TITLE
Correction in DAC 21 Paper

### ISSUE THREAD

**Issue by scanakci** [strongcourage/awesome-directed-fuzzing#1]
Hi,

Thank you for compiling all published works under this repo. I noticed that one paper title and link are wrong. Can you please correct the title and link?

[DAC'21] Regression Greybox Fuzzing should be  **[DAC'21] DirectFuzz: Automated Test Generation for RTL Designs using Directed Graybox Fuzzing**

Link to Paper-> https://ieeexplore.ieee.org/document/9586289

Thanks,

Sadullah

**Comment by strongcourage** [comment]
@scanakci Sorry Sadullah, I fixed it. Thank you.
