### ISSUE TITLE
On the Effectiveness of Synthetic Benchmarks for Evaluating Directed Grey-box Fuzzers

### ISSUE THREAD

**Issue by goodtaeeun** [strongcourage/awesome-directed-fuzzing#4]
Just in case you have missed this one.

Lee et al., On the Effectiveness of Synthetic Benchmarks for Evaluating Directed Grey-box Fuzzers, APSEC, 2023

https://softsec.kaist.ac.kr/~sangkilc/papers/lee-apsec23.pdf

Best,
Tae Eun.

**Comment by strongcourage** [comment]
Hi Tae Eun,

Thank you, I've already added it. This is indeed a very interesting paper on DGF.

Best.

**Comment by goodtaeeun** [comment]
Oops... I am very sorry for the mistake.
I am always admiring your effort on this project.

Thank you!
